### ISSUE TITLE
Add the projects (slack channel) name to the status if it has the same name with another one (from another project)

### ISSUE THREAD

**Issue by dnazarenkov** [cleverua/tuna-timer-api#16]
Now it looks like:

> •  _00:01h_  android regression testing
> •  _01:33h_  android regression testing

Lets make it looks like: 

> _00:01h_  _another project_ - android regression testing
> _01:33h_  - android regression testing

where _another project_ - the name of the channel where timer was started last

**Comment by xandrck** [comment]
👍
